name: usac_map_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  double_back_to_close_app: ^2.1.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.0.15
  syncfusion_flutter_pdfviewer: ^22.2.9
  url_launcher: ^6.1.12
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assests/logo.jpg"
  image_path: "assests/logo.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assests/uttarakhand_shasan.jpg"
    background_color: "#hexcode"
  windows:
    generate: true
    image_path: "assests/uttarakhand_shasan.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assests/uttarakhand_shasan.jpg"

flutter:
  uses-material-design: true
  assets:
    - assests/USAC_Bulding_1.jpg
    - assests/usac-logo.png
    - assests/logo.jpg
    - assests/uttarakhand_shasan.jpg

    - assests/thumbnails/cm.jpg
    - assests/thumbnails/governor.jpg

    - assests/thumbnails/solar_power_plant.webp
    - assests/thumbnails/power_transmission.webp
    - assests/thumbnails/power_generation.webp
    - assests/thumbnails/power_distribution.jpg


    # PDF Maps
    - assests/pdf_maps/power.pdf
    - assests/pdf_maps/power_substations.pdf
    - assests/pdf_maps/hydro_power_plants.pdf
    - assests/pdf_maps/population_heat.pdf
    - assests/pdf_maps/atlas.pdf